foundation.generate.group.exception.name.repeat=分组名 {0} 已存在 
